"""followers

Revision ID: 983758f86d8c
Revises: 2c65bb0e0c8d
Create Date: 2024-04-28 19:35:07.391951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '983758f86d8c'
down_revision = '2c65bb0e0c8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['web_user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['web_user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
